# This is a basic workflow to help you get started with Actions

name: TNB Daily Analysis

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "10 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8
      
      - uses: actions/cache@v2
        # if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Take backup
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
          python main.py
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Generate CSV
        run: |
          npm install
          node update.js
      - name: Generate charts
        run: python generate_plots.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }} 
      - name: Updated charts
        run: |
          git config --global user.name 'itsnikhil'
          git config --global user.email 'taneja.nikhil03@gmail.com@users.noreply.github.com'
          git add .
          git commit -m "Automated report"
          git push
