# This is a basic workflow to help you get started with Actions

name: TNB Daily Analysis

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: "0 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      - name: Install dependencies
        run: npm install
      - name: Generate CSV
        run: node main.js
      - name: Setup Python
        uses: actions/setup-python@v2.1.4
        with:
          python-version: 3.8
      - name: Generate charts
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python generate_plots.py
      - name: Updated charts
        run: |
          git config --global user.name 'itsnikhil'
          git config --global user.email 'taneja.nikhil03@gmail.com@users.noreply.github.com'
          git commit -am "Automated report"
          git push
